name: SonarCloud Quality Gate Check

on:
  workflow_dispatch:

jobs:
  sonarcloud-quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud temporarily disabled on PR
        run: echo "SonarCloud disabled for pull requests until properly configured."